List4 = {
    "Calm Down(+) Make Better": [
        "Allay",
        "Alleviate",
        "Ameliorate",
        "Appease",
        "Assuage",
        "Conciliate",
        "Extenuating",
        "Mitigate",
        "Mollify",
        "Pacify",
        "Placate",
        "Propitiated",
        "Solace",
        "Temper",
        "Exacerbate(Opposite)",
    ],
    "Crucial OR Significant": [
        "Core",
        "Foremost",
        "Imperative",
        "Indispensable",
        "Mandatory",
        "Momentous",
        "Paramount",
        "Pivotal",
        "Salient",
        "Linchpin",
    ],
    "Difficult To Understand": [
        "Abstract",
        "Abstruse",
        "Arcane",
        "Esoteric",
        "Mystical",
        "Obscure",
        "Occult",
        "Recondite",
        "Profound(+) OR Profundity",
        "Perspicuous(Opposite)",
    ],
    "End OR Stop": ["Terminate", "Culminate", "Cease", "Onset(Opposite)"],
    "Enthusiastic OR Excited": [
        "Arbor OR Ardent",
        "Avid",
        "Dynamic",
        "Ebullient",
        "Effervescent",
        "Effusive",
        "Exuberant",
        "Fervent OR Fervor",
        "Frisky",
        "Gushing",
        "Impassioned",
        "Vivacious",
        "Zealous OR Zest",
        "Dampen(Opposite)",
        "Tepid(Opposite)",
        "Rhapsody",
    ],
    "Happy OR Joyous": [
        "Beam",
        "Ecstasy",
        "Elated",
        "Euphoria",
        "Exhilaration",
        "Exultant",
        "Felicity",
        "Gaiety",
        "Jest",
        "Jocular",
        "Jocund",
        "Jollity",
        "Jovial",
        "Jubilant",
        "Rapturous",
        "Uproarious",
        "Regale",
    ],
    "Hardworking(+)": [
        "Assiduous",
        "Diligent",
        "Industrious",
        "Painstaking",
        "Sedulous",
        "Toil",
    ],
    "Irregular OR Periodically": [
        "Fitfully",
        "Intermittent",
        "Occasional",
        "Spasmodic",
        "Sporadic",
    ],
    "Lacking Energy OR Lazy(-)": [
        "Indolent",
        "Jaded",
        "Lackadaisical",
        "Lackluster",
        "Languid",
        "Lassitude",
        "Lethargic",
        "Listless",
        "Sloth",
        "Sluggish",
        "Torpor OR Torpid",
    ],
    "Never Ending OR Non-Stop": [
        "Chronic",
        "Incessant",
        "Inexorable",
        "Interminable",
        "Perennial",
        "Relentless",
    ],
    "Ordinary(-)": [
        "Banat",
        "Cliche",
        "Commonplace",
        "Derivative",
        "Hackney",
        "Humdrum",
        "Mundane",
        "Pedestrian",
        "Platitude",
        "Plebeian",
        "Quotidian",
        "Trite",
        "Unremarkable",
    ],
    "Related": ["Affiliated", "Kindred"],
    "Sad OR Depressed": [
        "Anguish",
        "Bereaved",
        "Bleak",
        "Crestfallen",
        "Dejected",
        "Desolate",
        "Despondent",
        "Forlorn",
        "Glum",
        "Lament",
        "Lugubrious",
        "Melancholy",
        "Plaintive",
        "Woe",
        "Pathos",
        "Poignant",
    ],
    "Short Lived": ["Ephemeral", "Evanescent", "Fleeting", "Transient", "Transitory"],
    "Unimportant OR Trivial": [
        "Expendable",
        "Fringe",
        "Incidental",
        "Inconsequential",
        "Marginalization",
        "Peripheral",
    ],
    "Unusual OR Exception": ["Aberration", "Anomaly", "Deviate"],
}
