List6 = {
    "Accept OR Agree OR Given In": [
        "Accede",
        "Acquiesce",
        "Amenable",
        "Assent",
        "Compliant",
        "Comply",
        "Concede",
        "Concur",
        "Pliant",
        "Relent",
        "Succumb",
        "Yield",
        "Docile(Easily Control)",
        "Malleable(Easily Control)",
    ],
    "Break a Rule": [
        "Breach",
        "Flout",
        "Transgress",
        "Abide(Opposite)",
        "Adhere(Opposite)",
        "Infraction",
    ],
    "Cancel OR Take Back": [
        "Annul",
        "Disavow",
        "Gainsay",
        "Null",
        "Recant",
        "Renege",
        "Repeal",
        "Repudiate",
        "Rescind",
        "Retract",
        "Revoke",
        "Void",
    ],
    "Clothing": ["Sartorial", "Raiment"],
    "Co-Existing": ["Contemporary", "Simultaneous"],
    "Determined(+)": [
        "Dogged",
        "Endure",
        "Immutable",
        "Indefatigable",
        "Persevere",
        "Persistence",
        "Resolute",
        "Steadfast",
        "Tenacious",
    ],
    "Energizing": ["Galvanizing", "Invigorating", "Revitalizing", "Rousing"],
    "Extra Hence Unnecessary": ["Extraneous", "Redundant", "Superfluous"],
    "Famous Person": ["Eminent", "Luminary", "Pre-Eminent", "Stature"],
    "Greed": [
        "Avarice",
        "Covetous",
        "Cupidity",
        "Glutton(Food)",
        "Rapacious",
        "Ravenous",
        "Voracious",
        "Mercenary(Materialistic)",
    ],
    "Overly Noise(-)": [
        "Cacophony",
        "Clamor",
        "Clangor",
        "Din",
        "Discordant",
        "Raucous",
        "Strident",
        "Uproar",
        "Vociferous",
        "Boisterous(Loud and Excited)",
        "Inaudible(Opposite)",
        "Obstreperous",
    ],
    "Planned OR Spontaneous (Opposite)": [
        "Calculated",
        "Deliberate",
        "Forethought",
        "Intentional",
        "Premeditated",
        "Studied",
        "Extemporaneous(Opposite)",
        "Impetuous(Opposite)",
        "Impromptu(Opposite)",
        "Improvise(Opposite)",
        "Offhand(Opposite)",
    ],
    "Pleasant Sounding": ["Euphony", "Melodious", "Mellifluous"],
    "Profitable": ["Remunerative", "Lucrative"],
    "Severe": ["Acute", "Austere"],
    "Stubborn(-)": [
        "Adamant",
        "Defiant",
        "Incorrigible",
        "Intractable",
        "Intransigent",
        "Obdurate",
        "Obstinate",
        "Pertinacious",
        "Perverse",
        "Recalcitrant",
        "Refractory",
        "Willful",
    ],
    "Supporter OR Enemy(Opposite)": [
        "Advocate",
        "Ally",
        "Champion",
        "Endorse",
        "Espouse",
        "Lobbyist",
        "Protagonist",
        "Tout",
        "Proponent",
        "Adversary(Opposite)",
        "Antagonist(Opposite)",
        "Detractor(Opposite)",
        "Foe(Opposite)",
        "Impugn(Opposite)",
        "Inimical(Opposite)",
        "Nemesis(Opposite)",
        "Opponent(Opposite)",
    ],
    "To Approach Something": ["Accost(-)", "Broach(+)"],
    "To Make Up OR Create": ["Concoct", "Devise", "Formulate", "Conjure"],
    "To Object OR Resist": ["Defy", "Demur", "Dissent", "Take Issue With"],
    "To Prove False OR To Disprove": [
        "Belie",
        "Debunk",
        "Discredit",
        "Expostulate",
        "Rebut",
        "Refute",
        "Remonstrate",
    ],
    "Urgent": ["Exigent", "Pressing"],
}
