List12 = {
    "Desiring Only Pleasure": ["Hedonist", "Sybarite"],
    "Dramatic Behavior": ["Histrionic", "Melodramatic"],
    "Exclude OR Forbid": ["Ostracize", "Shun", "Taboo"],
    "Frank": ["Candid OR Candor", "Forthright", "Vocal"],
    "Fully Satisfied": [
        "Gratify",
        "Quench",
        "Replete",
        "Satiate",
        "Saturate",
        "Suffice",
    ],
    "Fussy(-)": ["Finicky", "Nitpicking", "Persnickety", "Squeamish", "Stickler"],
    "Hint OR Indirect Reference": [
        "Allude OR Allusion",
        "Cue",
        "Implicit",
        "Innuendo",
        "Insinuate",
        "Tacit",
        "Blatant (Opposite)",
        "Explicit (Opposite)",
        "Cite (Opposite)",
    ],
    "Huge OR Big": [
        "Behemoth",
        "Colossal",
        "Gargantuan",
        "Gigantic",
        "Humongous",
        "Mammoth",
        "Monolithic",
        "Monumental",
        "Prodigious",
        "Titanic",
        "Towering",
        "Voluminous",
    ],
    "Insignificant": ["Marginal", "Minute", "Negligible", "Paltry", "Token", "Trifle"],
    "Lacking": ["Bereft", "Deprived", "Devoid", "Wanting"],
    "Long Essay OR Speech": ["Discourse", "Dissertation", "Rhetoric"],
    "Minor DIfferences": ["Nuances", "Subtle", "Shades"],
    "Mistake OR Act Done Carelessly": [
        "Botch",
        "Bungle",
        "Misnomer",
        "Tactless",
        "Finesse (Opposite)",
    ],
    "Pertaining To Religion": [
        "Agnostic",
        "Atheist",
        "Pious",
        "Proselytize",
        "Theist",
        "Theology",
    ],
    "Place Side By Side": ["Abut", "Adjacent", "Contiguous", "Juxtaposition"],
    "Remove OR Destroy": [
        "Annihilate",
        "Decimate",
        "Efface",
        "Eradicate",
        "Expunge",
        "Exterminate",
        "Extirpate",
        "Obliterate",
        "Perish",
        "Raze",
        "Indelible (Opposite)",
        "Devastate",
        "Excise",
    ],
    "Small": ["Slight", "Minuscule", "Infinitesimal", "Diminutive"],
    "Strengthen OR Support": [
        "Bastion",
        "Bolster",
        "Buttress",
        "Fortify",
        "Prime",
        "Prop",
    ],
    "Sympathy": ["Compassion", "Empathy", "Callous (Opposite)"],
    "Theory Without Evidence": ["Hypothetical", "Speculate", "Empirical (Opposite)"],
    "Thorough OR Precise": [
        "Conscientious",
        "Fastidious",
        "Meticulous",
        "Nice",
        "Punctilious",
        "Purist",
        "Scrupulous",
    ],
    "To Do Happily (+)": ["Alacrity", "Obliging"],
    "To Do Reluctantly OR Unwillingly (-)": ["Balk", "Grudging"],
    "To Guess OR Infer": [
        "Conjecture",
        "Construe",
        "Deduce",
        "Extrapolate",
        "Surmise",
        "Inductive",
    ],
    "Understand": [
        "Apprehend",
        "Assimilate",
        "Comprehend",
        "Fathom",
        "Intelligible",
        "Illegible (Opposite)",
    ],
    "Used To": ["Habituate", "Immune", "Inure", "Inveterate"],
    "Weak OR Fragile": [
        "Flimsy",
        "Frail",
        "Intangible",
        "Tenuous",
        "Palpable (Opposite)",
        "Substantial (Opposite)",
        "Tactile (Opposite)",
        "Corporeal",
    ],
    "Weaken": ["Erode", "Undercut", "Undermine", "Subvert", "Undergird (Opposite)"],
}
