List14 = {
    "After Effects": ["Ramifications", "Repercussions", "Ensue"],
    "Bad Smell": ["Noisome", "Rank"],
    "Exaggerate": ["Hyperbole", "Underplay (Opposite)", "Understae (Opposite)"],
    "Excusable": ["Venial"],
    "Farewell": ["Valedictory", "Parting"],
    "Harsh OR Biting OR Sharp": [
        "Acerbic",
        "Acrimonious",
        "Caustic",
        "Incisive",
        "Scathing",
        "Trenchant",
        "Euphemism (Opposite)",
    ],
    "Hesitate On Moral Grounds": [
        "Compunction",
        "Misgivings",
        "Qualms",
        "Scruples",
        "Unscrupulous (Opposite)",
    ],
    "Inactive": ["Dormant", "Latent", "Quiescent", "Stagnant"],
    "Independence OR Freedom": ["Autonomy", "Latitude", "Sovereign"],
    "Indirect Experience": ["Vicarious"],
    "Inferior Rank": ["Relegate", "Demote"],
    "Reveal OR Hide": [
        "Divulge",
        "Telling",
        "Conceal (Opposite)",
        "Secrete (Opposite)",
    ],
    "Revenge": ["Vengeance", "Vindictive", "Retribution"],
    "Seller": ["Purveyor", "Vendor"],
    "Spiritual OR Earthy (Opposite)": ["Sublime", "Base (Opposite)"],
    "Story": ["Anecdote", "Narrative"],
    "To Put On": ["Don"],
    "To Rise Beyond": ["Outclass", "Transcend"],
    "To Stir Up OR Revolt": [
        "Goad",
        "Incite",
        "Incendiary",
        "Instigate",
        "Provoke",
        "Sedition",
        "Foment",
    ],
    "Variety": [
        "Diversity",
        "Eclectic",
        "Motley",
        "Multifaceted",
        "Multifarious",
        "Sundry",
        "Veriegate",
        "Versatile",
    ],
    "Village Like": ["Bucolic", "Pastoral", "Rustic"],
}
